# Generated by Django 3.0.2 on 2020-01-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuser',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='validation_key',
        ),
    ]
